export const AUTH_ROLES_KEY = 'camiones:auth:roles';

export const AUTH_ACTOR_HEADER = 'x-actor';
export const AUTH_ROLE_HEADER = 'x-role';

export enum AuthRole {
  ADMIN = 'ADMIN',
  LOGISTICS_MANAGER = 'LOGISTICS_MANAGER',
  DISPATCH_OPERATOR = 'DISPATCH_OPERATOR',
  WAREHOUSE_OPERATOR = 'WAREHOUSE_OPERATOR',
  CUSTOMS_OPERATOR = 'CUSTOMS_OPERATOR',
  GATE_OPERATOR = 'GATE_OPERATOR',
  LOADING_SUPERVISOR = 'LOADING_SUPERVISOR',
}
