export enum OperationStatus {
  DRAFT = 'DRAFT',
  PLAN_GENERATED = 'PLAN_GENERATED',
  APPROVED = 'APPROVED',
  CANCELLED = 'CANCELLED',
}

export enum LoadingMethod {
  REAR = 'REAR',
  SIDE = 'SIDE',
  TOP = 'TOP',
  MIXED = 'MIXED',
}

export enum TruckZoneType {
  CABIN_SIDE = 'CABIN_SIDE',
  CENTER = 'CENTER',
  DOOR_SIDE = 'DOOR_SIDE',
}

export enum ProductFamily {
  COIL = 'COIL',
  SHEET = 'SHEET',
  PROFILE = 'PROFILE',
  TUBE = 'TUBE',
  BAR = 'BAR',
  GENERIC_PACKAGE = 'GENERIC_PACKAGE',
}

export enum PlanStatus {
  GENERATED = 'GENERATED',
  MODIFIED = 'MODIFIED',
  APPROVED = 'APPROVED',
  INVALID = 'INVALID',
}

export enum UnplacedReason {
  DOES_NOT_FIT = 'DOES_NOT_FIT',
  EXCEEDS_WEIGHT = 'EXCEEDS_WEIGHT',
  NO_AVAILABLE_SPACE = 'NO_AVAILABLE_SPACE',
  STACKING_RESTRICTION = 'STACKING_RESTRICTION',
  MANUAL_REVIEW_REQUIRED = 'MANUAL_REVIEW_REQUIRED',
}

export enum AlertSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum AlertType {
  MAX_WEIGHT_EXCEEDED = 'MAX_WEIGHT_EXCEEDED',
  OUT_OF_BOUNDS = 'OUT_OF_BOUNDS',
  OVERLAP = 'OVERLAP',
  HEIGHT_EXCEEDED = 'HEIGHT_EXCEEDED',
  UNPLACED_ITEM = 'UNPLACED_ITEM',
  WEIGHT_IMBALANCE = 'WEIGHT_IMBALANCE',
  DESTINATION_BLOCKED = 'DESTINATION_BLOCKED',
  STACKING_RISK = 'STACKING_RISK',
  MANUAL_REVIEW_REQUIRED = 'MANUAL_REVIEW_REQUIRED',
}
